<?php
	include_once "header.php";
?>

<body class="tutorial-page">

<?php
	include_once "navbar.php";
?>

<div class="wrapper">
	<div class="header header-filter" style="background-image: url('assets/img/cgu.jpg');">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					<h1 class="title text-center">Conditions Générales d'Utilisation</h1>
				</div>
			</div>
		</div>
	</div>

	<div class="main main-raised">
		<div class="section">
	    <div class="container">
				<div class="row tim-row">
	                <h2 class="text-center">Définitions</h2>
	                <legend></legend>
	                <div class="col-md-8 col-md-offset-2">
                    <br />
<div class=""><p>On désignera par la suite:</p><ul><li><strong>« Site »</strong> ou <strong>« Service »</strong> : le site http://www.belle-table.fr/ et l'ensemble de ses pages.</li><li><strong>« Editeur »</strong> : Elias HAMADOUCHE, personne morale ou physique responsable de l'édition et du contenu du Site.</li><li><strong>« Utilisateur »</strong> : l'internaute visitant et utilisant les Services du Site.</li></ul><p>Les présentes Conditions Générales d’Utilisation (ci-après les « CGU ») sont proposées par l'Editeur du Site. L'Utilisateur du Site est invité à lire attentivement ces CGU, à les imprimer et/ou à les sauvegarder sur un support durable. L'Utilisateur reconnaît avoir pris connaissance des CGU et les accepte intégralement et sans réserve.</p></div>
<div><h3 style="color:#000;margin:30px 0 10px 0;padding:0;font-size:16px;font-weight:bold;" class="review-section"><span style='margin-left:0px;'>Article 1 - <span style='margin-left:10px;'></span>Application des CGU</span></h3>
<div class="" title="Section disponible après achat"><p>Les présentes CGU ont pour objet de définir les conditions d'accès au Site par les Utilisateurs. L'Editeur se réserve le droit de modifier à tout moment les CGU en publiant une nouvelle version de ces dernières sur le Site. <strong>Les CGU applicables à l'Utilisateur sont celles en vigueur au jour de son acceptation</strong>. </p><p>Le Site est d'accès libre et gratuit à tout Utilisateur. L'acquisition d'un produit ou d'un service, ou la création d'un espace membre, ou de manière plus générale la navigation sur le Site suppose l'acceptation, par l'Utilisateur, de l'intégralité des présentes CGU, qui reconnaît du même fait en avoir pris pleinement connaissance.</p><p>Cette acceptation pourra consister par exemple, pour l'Utilisateur, à cocher la case correspondant à la phrase d'acceptation des présentes CGU, ayant par exemple la mention « <em>je reconnais avoir lu et accepté l'ensemble des conditions générales du Site</em> ». Le fait de cocher cette case sera réputé avoir la même valeur qu'une signature manuscrite de la part de l'Utilisateur.</p><p>L'Utilisateur reconnaît la valeur de preuve des systèmes d'enregistrement automatique de l'Editeur du présent Site et, sauf pour lui d'apporter une preuve contraire, il renonce à les contester en cas de litige.</p><p>L'acceptation des présentes CGU suppose de la part des Utilisateurs qu'ils jouissent de la capacité juridique nécessaire pour cela. Si l'Utilisateur est mineur ou ne dispose pas de cette capacité juridique, il déclare avoir l'autorisation d'un tuteur, d'un curateur ou de son représentant légal.</p></div></div>
<div><h3 style="color:#000;margin:30px 0 10px 0;padding:0;font-size:16px;font-weight:bold;" class="review-section"><span style='margin-left:0px;'>Article 2 - <span style='margin-left:10px;'></span>Mentions légales, données personnelles et objet du Site</span></h3>
<div class="" title="Section disponible après achat"><p>Le présent Site est édité par Elias HAMADOUCHE SARL. Les informations légales concernant l'hébergeur et l'Editeur du Site, notamment les coordonnées et les éventuelles informations de capital et d'immatriculation, sont fournies dans les mentions légales du présent Site.</p><p>Les informations concernant la collecte et le traitement des données personnelles (politique et déclaration) sont fournies dans la charte de données personnelles du Site.</p><p>L'objet du présent Site est déterminé comme « Site de location en ligne et de concours ».</p></div></div>
<div><h3 style="color:#000;margin:30px 0 10px 0;padding:0;font-size:16px;font-weight:bold;" class="review-section"><span style='margin-left:0px;'>Article 3 - <span style='margin-left:10px;'></span>Espace membre</span></h3>
<div class="" title="Section disponible après achat"><p>L'Utilisateur inscrit au Site (membre) a la possibilité d’y accéder en se connectant grâce à ses identifiants (adresse e-mail définie lors de son inscription et mot de passe) ou éventuellement en utilisant des systèmes tels que des boutons de connexion tiers de xxxxxxxx sociaux. L'utilisateur xxx entièrement responsable xx la protection xx mot de xxxxx qu’il a xxxxxxx Il est xxxxxxxxxx à utiliser xxx mots de xxxxx complexes. En xxx d’oubli du xxx de passe, xxxxxxxxxxxxx a la xxxxxxxxxxxx d’en générer xx nouveau. Ce xxx de xxxxx xxxxxxxxx xx garantie xx la xxxxxxxxxxxxxxxx xxx xxxxxxxxxxxx contenues xxxx sa xxxxxxxx xx xxx compte xx et xxxxxxxxxxxxx xxxxxxxxxx xxxx de xx transmettre xx xx xx communiquer xx un xxxxxx x xxxxxxxx l'Editeur xx Site xx xxxxxx xxxxx tenu xxxx responsable xxx xxxxxx xxx autorisés xx compte xxxx xxxxxxxxxxxx</p><p>xx xxxxxxxxx d’un xxxxxx personnel xxx xx xxxxxxxxxx indispensable xx toute xxxxxxxx xx xxxxxxxxxxxx de xxxxxxxxxxxxx sur xx xxxxxxxx xxxxx A xxxxx fin, xxxxxxxxxxxxx xxxx xxxxxxx à xxxxxxx un xxxxxxx xxxxxx xxxxxxxxxxxxxxxx personnelles. xx s’engage xx xxxxxxx xxx informations xxxxxxxx</p><p>xx collecte xxx xxxxxxxx x pour xxxxx la xxxxxxxxx xxxxxx xx compte xxxxxx ». xx xxx xxxxxxxx contenues xxxx la xxxxxxxx xxxxxx xxxxxx venaient xx disparaître xx xx xxxxx d’une xxxxx technique xx xxxxxx xxx de xxxxx majeure, xx xxxxxxxxxxxxxxx xx Site xx de xxx xxxxxxx xx pourrait xxxxx engagée, xxx xxxxxxxxxxxx xxxxxxxxx aucune xxxxxx probante xxxx xxxxxxxxxx xx caractère xxxxxxxxxxx Les xxxxx xxxxxxxxx xxx comptes xxxxxxx sont xxxxxxxxx xxxxxxxxxxx xxx le xxxxxxxxx du xxxxxx xx xxxxxxxx mais xx constituent xxxxxxxxx xxx xxxxxxx elles xxxxxxx qu’un xxxxxxxxxx xxxxxxxxxx xxxxxxxx à xxxxxxx une xxxxxxx xxxxxxxx xx service xx des xxxxxxxxxxxxx xxx xxxxxxxxxxxxxx</p><p>xxxxxx Utilisateur xxx libre xx xxxxxx xxx xxxxxx xx xxx xxxxxxxx xxx xx xxxxx xxxx xxxxx xx xxxx xxxxxxxx xx xxxxxx xx Elias HAMADOUCHE xxxxxxxxx xxxxxxx xxxxxxxx xxxxxxxxx xxx xxxxxxx xxxxxx xxxxxxxxxxxxxx xx xxx xxxxxxxx xx xxxx xxxxx xxxxxxxxx</p><p>xxxxxxxxx xx xxxxxxxx xx xxxxx xxxxxxxx xx xxxxxxxxx xx xxxxxx xx xxxx xxxxxxxxxxx xxx xxxxxx xxxxxxxxxx xxx xxxxxxxxxx xxx xxxxxxxxxxx xxxx xxxx xxx xxx xxxxxxx xxxxxxx xx xxxxxxxxxx xxxxxxxxxx xxxxxxxxxx xxxxxxx xxxxxxxxxxxxx xxxx xxxxxx xxxxxxxxx xxx xxxxxxxxxxxx xxxxxxxxxx xxxx xx xxx xxxxxxxxxxx xx xx xx xxxxxxxxxxxx xx xxx xxxxxx xxxxxxxxxx xx xxxxxx xxxx xxxxxx xxxxxxx xxxxxx xx xxxxx xxx xxxxxxx xxxxxx xxxxxxxxxxx xx xxxx xxx xxxxxxxxxxx xx xxxxxxxxxx xx xxxxxxx xxxx xxxxxxxxxxxxx xxxxx xxx xx xxxxxx xxxxxxxxxx xx xxxxxx xxxxxxxxxx xx xx xxxxx xxxxx xxxxxxxxx xxxxxxx xxx xxxxxxxxx xx xx xxxxxxxxxxxxx xxxx xxxxxxxxxx xxxxxxxxxxxxxxxx xxx xxxxxxxxxx xxxxxxxxx xxxxxxxxxx xx xxxxxxxxxxxx xx xxxxxxxxxxxxxx xxxxxxx xxx xxxxx xxxxxxxxxx xxxxxxxxxx</p> </div></div>
<div><h3 style="color:#000;margin:30px 0 10px 0;padding:0;font-size:16px;font-weight:bold;" class="review-section"><span style='margin-left:0px;'>Article 4 - <span style='margin-left:10px;'></span>Accès et disponibilité du Site</span></h3>
<div class="" title="Section disponible après achat"><p>L'Editeur fait ses meilleurs efforts pour rendre le Site accessible en permanence, sous réserve des opérations de maintenance du Site ou xxx serveurs sur xxxxxxxx il est xxxxxxxxxx En cas xxxxxxxxxxxxxxxxxx d’accès au xxxxx en raison xx problèmes techniques xx de toutes xxxxxxxx l'Utilisateur xx xxxxxx xx prévaloir xxxx dommage xx xx xxxxxx prétendre xx aucune xxxxxxxxxxx</p><p>xxxxxxxxx xx xxxx n’est xxxx que xxx xxx xxxxxxxxxx de xxxxxx ; xx xxxxxxxxxxxxxxx xx pourra xxxxx engagée xxxx xx xxxxxxx résultant xx l'utilisation xx xxxxxxx xxxxxxxx tel xxx perte xx xxxxxxxxx xxxxxxxxxx virus, xxxxxxx du xxxxxxxx xx xxxxxxx</p><p>xxxxxxxxxxxxx admet xxxxxxxxxxxxx utiliser xx xxxx xx ses xxxxxxx risques xx xxxx xx responsabilité xxxxxxxxxx</p><p>xx Site xxxxxxx xx xxxxxxxxxxxxx des xxxxxxxxxxxx à xxxxx xxxxxxxxxx xxxx des xxxxxxxxxxxxxx erreurs, xxxxxxxxxx xxxxxxxxxxxxx xx autres xxxxxxxxxxxx susceptibles xxxxxxxxxx xx xxxx état xx cause, Elias HAMADOUCHE xx xxxxxx en xxxxx cas xxxxx xxxx xxxxxxxxxxx x</p><ul><li>xx xxxx xxxxxxx xxxxxx xx xxxxxxxxx xxxxxxxxx xx xx xxx xxxxxxxx xxx xxxxxx xx xxxxxxxx xx xxxxxx xx xxxxxxx xxx xxxxxx xx xxxxxxxxxxx xx xxxxxxxx xxxxxxx xxxxx xxxxxx xxxxxxxxx xx xxxxxxxxxxxxx xx xxxxx xx xx xxxxxxxxx xx xxxxxxxxxxxxxxxx xx xxx xxxxxxxxxxx x</li><li>xxxx xxxxxxxxxxxxxxxxxx xxxxx xxxxxxxxxxxxxxxx xxxxxxxxx xxxxx xxxxxxxx xxxxxxxxxxxx xxxxx xxxxxxxx xxxxxxxxxxxxx xx xxxxxxxxxxxx xx xxxxxxxxxxxxxx xx xxxxxx xx xxxxxxxx xxxx xxxxxxxxxx xxx xxxxxx xxx xxxxxxxxxxxxxx</li></ul> </div></div>
<div><h3 style="color:#000;margin:30px 0 10px 0;padding:0;font-size:16px;font-weight:bold;" class="review-section"><span style='margin-left:0px;'>Article 5 - <span style='margin-left:10px;'></span>Liens hypertextes</span></h3>
<div class="" title="Section disponible après achat"><p>Le Site peut inclure des liens hypertextes vers d’autres sites.</p><p>L'Utilisateur reconnaît par conséquent que l'Editeur ne pourra être tenu responsable de tous dommages ou pertes avérés ou allégués, consécutifs à ou en relation avec l'utilisation ou avec le fait d'avoir pris connaissance des contenus, publicités, produits ou services disponibles sur ces sites ou sources externes. De même, la responsabilité de l'Editeur du présent Site ne saurait être engagée si la visite, par l’Utilisateur, de l’un de ces sites, lui causait un préjudice.</p><p>Si, en dépit des efforts de l'Editeur, un des liens hypertextes présents sur le Site pointait vers un site ou une source internet dont le contenu était ou paraissait non conforme aux exigences de la loi française à un Utilisateur, celui-ci s’engage à prendre immédiatement contact avec le directeur de la publication du Site, dont les coordonnées figurent dans les mentions légales du Site, afin de lui communiquer l'adresse des pages du site tiers en cause.</p></div></div>
<div><h3 style="color:#000;margin:30px 0 10px 0;padding:0;font-size:16px;font-weight:bold;" class="review-section"><span style='margin-left:0px;'>Article 6 - <span style='margin-left:10px;'></span>Cookies</span></h3>
<div class="" title="Section disponible après achat"><p>Un « Cookie » peut permettre l'identification de l'Utilisateur du Site, la personnalisation de sa consultation du Site xx l'accélération de xxxxxxxxxxxxx du Site xxxxxx à l'enregistrement xxxx fichier de xxxxxxxx sur son xxxxxxxxxxx xx Site xxx susceptible xxxxxxxxxx xxx xx Cookies xx principalement xxxx xx xxxxxxx des xxxxxxxxxxxx de xxxxxxxxxx xxxx xxxxxxxxxxxx l'expérience xx l'Utilisateur, xx xx xxxxxxxxx l'accès xx un xxxxxx xx xxxxxx et xx du xxxxxxx xxx xxxxx pas xxxxxxxxxx sans xxxxxxxxxx</p><p>xxxxxxxxxxxxx xxxxxxxxxx xxxxx informé xx cette xxxxxxxx xx xxxxxxxx l'Editeur xx Site xx x xxxxxxxxx L'Editeur xxxxxxxx à xx xxxxxx xxxxxxxxxxx le xxxxxxx de xxx xx xxxxxxx » xx des xxxxxxx xxxxxxxxxx xxxx en xxx de xxxxxxxxxxxx xxxxxxxx</p><p>xxxxxxxxxxxxx xxxx xxxxxxx xxxxxxxxxxxxxxxx xx xx xxxxxxx xx xx xxxxxxxxxx xxx xxxxxxxxxx xxxx xxxxx xxxxxxxx xxxxxxxxxxxxxx xx xxxxxxxxxxx xxx xx xxxxxxx xxx xxxx xx xxxxxx xxxxxxxxxxxxx xxxxxxxxxx xx xxxxxxxxxxxx xx xxx xxxxxxxxxx x</p><ul><li>xxxx xxxxxxxx xxxxxxxx x <a href="http://windows.microsoft.com/fr-FR/windows-vista/Block-or-allow-cookies">xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</a></li><li>xxxx xxxxxx x <a href="https://support.apple.com/fr-fr/ht1677">xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</a></li><li>xxxx xxxxxx xxxxxx x <a href="https://support.google.com/chrome/answer/95647?hl=fr&amp;hlrm=en&amp;safe=on">xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&amp;xxxxxxx&amp;xxxxxxx</a></li><li>xxxx xxxxxxx x <a href="https://support.mozilla.org/fr/kb/activer-desactiver-cookies">xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</a></li><li>xxxx xxxxx x <a href="http://help.opera.com/Windows/10.20/fr/cookies.html">xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</a></li></ul> </div></div>
<div><h3 style="color:#000;margin:30px 0 10px 0;padding:0;font-size:16px;font-weight:bold;" class="review-section"><span style='margin-left:0px;'>Article 7 - <span style='margin-left:10px;'></span>Droits de propriété intellectuelle</span></h3>
<div class="" title="Section disponible après achat"><p>Tous les éléments du présent Site appartiennent à l'Editeur ou à un tiers mandataire, ou sont utilisés par xxxxxxxxx sur le xxxx avec l'autorisation xx leur propriétaire.</p><p><strong>Toute xxxxxxxxxxxxxxxx reproduction ou xxxxxxxxxx des logos, xxxxxxxx xxxxxxxxx pictographiques xx vidéos, xxxx xxx xxxxx énumération xx soit xxxxxxxxxxx xxx xxxxxxxxxxxxxx interdite xx s’apparente xx xx xx contrefaçon</strong>.</p><p>Tout xxxxxxxxxxx qui xx xxxxxxxx xxxxxxxx de xxxxxxxxxxxx serait xxxxxxxxxxx xx xxxx son xxxxxx au xxxx xxxxxxxxx xxxx préavis xx indemnité xx xxxx xxx cette xxxxxxxxx ne xxxxxx xxx xxxxx constitutive xxxxxx dommage, xxxx xxxxxxxx xxxxxxxxxxxxxxxx poursuites xxxxxxxxxxx ultérieures xx xxx xxxxxxxxx à xxxxxxxxxxxxxx de xxxxxxxxxxx xx xxxxxxxx Site xx de xxx xxxxxxxxxxx</p><p>Le présent Site utilise des éléments (images, photographies, contenus) dont les crédits reviennent à : Belle Table.</p><p>xxx xxxxxxx xx xxxxx xxxxxxxx xxxx xx xxxx xxxx xxxxxxxxxxxx xxxxxxx xxxxxxxxx xxx Elias HAMADOUCHEx xx xxxxxxxxxxxxxxx xxx xx xx xxx xxxxxxxxxxxx xxxxx xxxxxxxx xxxxxxxxxx xx xxxxx xxxxxxxxxxxxxxxxx xxxxxxxxxxxxxx xxxxxxxxxxxxx xxxxxxxxxx xx xxxxxxxxxxxx xxxxxxx xxx xxxxxxxxx xxxxxxxx xxx xxxxxxxx xxxxxxx xx xxxxxxxx xx xxxx xx xx xxxxxxxxxxx xxxxxxxxxxxxxxx</p> </div></div>
<div><h3 style="color:#000;margin:30px 0 10px 0;padding:0;font-size:16px;font-weight:bold;" class="review-section"><span style='margin-left:0px;'>Article 8 - <span style='margin-left:10px;'></span>Responsabilité</span></h3>
<div class="" title="Section disponible après achat"><p>L'Editeur n’est pas responsable des publications des Utilisateurs, de leur contenu ainsi que de leur véracité. L'Editeur ne peut en aucun cas être tenu responsable de tout dommage susceptible d'intervenir sur le système informatique de l’Utilisateur et/ou de la perte de données résultant de l'utilisation du Site par l’Utilisateur.</p><p>L'Editeur s'engage à constamment mettre à jour le contenu du Site et à fournir aux Utilisateurs des informations justes, claires, précises et réactualisées. Le Site est en principe accessible en permanence, sauf pendant les opérations techniques de maintenance et de mise à jour du contenu. L'Editeur ne saurait être tenu responsable de dommages résultant de l’indisponibilité du Site ou de parties de celui-ci.</p><p>La responsabilité de l'Editeur du Site ne peut être engagée en raison d'une indisponibilité technique de la connexion, qu'elle soit due notamment à un cas de force majeure, à une maintenance, à une mise à jour, à une modification du Site, à une intervention de l'hébergeur, à une grève interne ou externe, à une panne de réseau, ou encore à une coupure d'alimentation électrique.</p><p>L'Editeur ne saurait être tenu responsable du non fonctionnement, d'une impossibilité d'accès ou de dysfonctionnements du Site imputables à un équipement non adapté, à une mauvais configuration ou utilisation de l'ordinateur de l'Utilisateur, à des dysfonctionnements des services du fournisseur d'accès des Utilisateurs, ou à ceux du réseau internet.</p></div></div>
<div><h3 style="color:#000;margin:30px 0 10px 0;padding:0;font-size:16px;font-weight:bold;" class="review-section"><span style='margin-left:0px;'>Article 9 - <span style='margin-left:10px;'></span>Contribution des Utilisateurs au contenu du Site</span></h3>
<div class="" title="Section disponible après achat"><p>Les Utilisateurs se voient offrir la faculté de contribuer au contenu du présent Site. Les Utilisateurs sont informés que l'Editeur du Site, représenté le cas échéant par les modérateurs, peut choisir de publier le contenu en question sur les newsletters de ce Site et sur les sites de tous ses partenaires, à charge pour l'Editeur de citer le pseudonyme de l'auteur de la contribution.</p><p>L’auteur renonce donc à ses droits sur le contenu des contributions, au profit de l'Editeur du Site, pour toute diffusion ou utilisation, même commerciale, sur le support internet, ceci, bien évidemment, toujours dans le respect de la paternité de l’auteur.</p></div></div>
<div><h3 style="color:#000;margin:30px 0 10px 0;padding:0;font-size:16px;font-weight:bold;" class="review-section"><span style='margin-left:0px;'>Article 10 - <span style='margin-left:10px;'></span>Limitation géographique d’utilisation</span></h3>
<div class="" title="Section disponible après achat"><p>L’utilisation des Services du Site est limitée à la France.</p></div></div>
<div><h3 style="color:#000;margin:30px 0 10px 0;padding:0;font-size:16px;font-weight:bold;" class="review-section"><span style='margin-left:0px;'>Article 11 - <span style='margin-left:10px;'></span>Notifications et réclamations</span></h3>
<div class="" title="Section disponible après achat"><p>Toute notification ou avis concernant les présentes CGU, les mentions légales ou la charte de données personnelles doit être faite par écrit et envoyée par courrier recommandé ou certifié, ou par mail à l'adresse indiquée dans les mentions légales du Site, en précisant les coordonnées, nom et prénom du notifiant, ainsi que l'objet de l’avis.</p><p>Toute réclamation liée à l'utilisation du Site, des Services, des pages du Site sur des réseaux sociaux éventuels ou aux CGU, aux mentions légales ou à la charte de données personnelles doit être déposée dans les 365 jours suivant le jour d’origine du problème source de réclamation, et ce indépendamment de toute loi ou règle de droit contraire. Dans le cas où une telle réclamation n’aurait pas été déposée dans les 365 jours suivants, une telle réclamation sera à jamais inapplicable en justice.</p><p>Il peut être possible que se trouvent, dans l'ensemble du Site internet et des Services proposés, et dans une mesure restreinte, des inexactitudes ou des erreurs, ou des informations qui soient en désaccord avec les CGU, les mentions légales ou la charte de données personnelles. En outre, il est possible que des modifications non autorisées soient faites par des tiers sur le Site ou sur des Services annexes (réseaux sociaux…).</p><p>Dans une telle situation, l'Utilisateur a la possibilité de contacter l'Editeur du Site par courrier postal ou par mail aux adresses indiquées dans les mentions légales du Site, avec si possible une description de l’erreur et l'emplacement (URL), ainsi que des informations suffisantes permettant de le contacter.</p></div></div>
<div><h3 style="color:#000;margin:30px 0 10px 0;padding:0;font-size:16px;font-weight:bold;" class="review-section"><span style='margin-left:0px;'>Article 12 - <span style='margin-left:10px;'></span>Indépendance des clauses</span></h3>
<div class="" title="Section disponible après achat"><p>Si une disposition des CGU est jugée illégale, nulle ou pour toute autre raison inapplicable, alors cette disposition sera réputée divisible des CGU et n'affectera pas la validité et l'applicabilité des dispositions restantes.</p><p>Les CGU remplacent tous accords antérieurs ou contemporains écrits ou oraux. Elles ne sont pas cessibles, transférables ou sous-licenciables par l'Utilisateur lui-même.</p><p>Une version imprimée des CGU et de tous les avis donnés sous forme électronique pourra être demandée dans des procédures judiciaires ou administratives en rapport avec les CGU. Les parties conviennent que toute la correspondance relative à ces CGU doit être rédigée dans la langue française.</p></div></div>
<div><h3 style="color:#000;margin:30px 0 10px 0;padding:0;font-size:16px;font-weight:bold;" class="review-section"><span style='margin-left:0px;'>Article 13 - <span style='margin-left:10px;'></span>Loi applicable</span></h3>
<div class="" title="Section disponible après achat"><p>Les présentes CGU sont régies par et soumises au droit Français.</p><p>Sauf dispositions d’ordre public, tous litiges qui pourraient survenir dans le cadre de l’exécution des présentes CGU pourront avant toute action judiciaire être soumis à l’appréciation de l'Editeur du Site en vue d’un règlement amiable.</p><p>Il est expressément rappelé que les demandes de règlement amiable ne suspendent pas les délais ouverts pour intenter les actions judiciaires.</p><p>Sauf disposition contraire, d’ordre public, toute action judiciaire relative à l’exécution des présentes CGU devra être soumise à la compétence des juridictions du ressort du lieu du domicile du défendeur.</p></div></div>
<p style='margin-top:40px;text-align:right;'>Tous droits réservés - 6 février 2018</p>
</div>
                  </div>
        </div>


	        </div>
	    </div>
	</div>

</div>

<?php
  include_once "footer.php";
 ?>

</body>
	<!--   Core JS Files   -->
	<script src="assets/js/jquery.min.js" type="text/javascript"></script>
	<script src="assets/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="assets/js/material.min.js"></script>

	<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
	<script src="assets/js/nouislider.min.js" type="text/javascript"></script>

	<!--  Plugin for the Datepicker, full documentation here: http://www.eyecon.ro/bootstrap-datepicker/ -->
	<script src="assets/js/bootstrap-datepicker.js" type="text/javascript"></script>

	<!-- Control Center for Material Kit: activating the ripples, parallax effects, scripts from the example pages etc -->
	<script src="assets/js/material-kit.js" type="text/javascript"></script>

	<script>

		$().ready(function(){

			$(window).on('scroll', materialKit.checkScrollForTransparentNavbar);

		});

</script>
</html>
